kind = "mobile"
previewPath = "/"
title = "nascard"
version = "1.0.0"
id = "artifacts/nascard"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25453

[services.development]
run = "pnpm --filter @workspace/nascard run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nascard", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/nascard", "run", "serve" ]

[services.env]
PORT = "25453"
BASE_PATH = "/"
